version: 2.1
orbs:
  on-demand-runner: cci-labs/on-demand-runner@dev:alpha
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  run-test-on-runner:
    machine: true
    resource_class: crowley-namespace/<< pipeline.id >>
    steps:
      - run: echo "Hello World! I am running on a On Demand Runner!"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - on-demand-runners/deploy:
          filters: *filters
          context: CPE_ORBS_AWS
          resource_class: << pipeline.id >>
      - run-test-on-runner:
          filters: *filters
          requires:
            - on-demand-runners/deploy
      - on-demand-runners/destroy:
          filters: *filters
          context: CPE_ORBS_AWS
          resource_class: << pipeline.id >>
          requires:
            - "run-test-on-runner"
            - "on-demand-runners/deploy"
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: cci-labs/on-demand-runner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - on-demand-runners/destroy
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
