---
- name: Create Resource Class
  uri:
    url: https://runner.circleci.com/api/v2/runner/resource
    method: POST
    body_format: json
    body:
      {
        "resource_class": "{{ NAMESPACE }}/{{ RESOURCE_CLASS }}",
        "description": "On demand Runner!",
      }
    status_code: 201
    headers:
      circle-token: "{{ CIRCLE_TOKEN }}"
  delegate_to: 127.0.0.1
