---
- name: Terminate EC2 Instances
  ec2_instance:
    name: "{{ NAMESPACE }}-{{ RESOURCE_CLASS }}-{{ item }}"
    wait: false
    state: terminated
  loop: "{{ range(0, NUMBER_OF_RUNNERS | int) | list }}"

- name: Gather information about any instance with Name beginning with {{ NAMESPACE }}-{{ RESOURCE_CLASS }}-*
  ec2_instance_info:
    filters:
      "tag:Name": "{{ NAMESPACE }}-{{ RESOURCE_CLASS }}-{{ item }}"
  register: ec2_node_info
  until: ec2_node_info.instances[0].state.name == "terminated"
  retries: "{{ UNTIL_RETRIES_RUNNERS }}"
  delay: 10
  loop: "{{ range(0, NUMBER_OF_RUNNERS | int) | list }}"

- name: Delete EC2 Dynamic Inventory File
  file:
    path: "aws_ec2.yml"
    state: absent
  when: (TEMPLATE_DYNAMIC_INVENTORY | bool == true )
